version: '2'

networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME} 

services:
  vertica:
    build: .
    image: vertica
    container_name: vertica
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_PTRACE
    volumes:
      - ./vertica-9.0.1-0.x86_64.RHEL6.rpm:/tmp/vertica.rpm
      - ./data:/opt/vertica
    
